name: quran_reading_correction_ai
description: تطبيق لتصحيح تلاوة القرآن الكريم باستخدام الذكاء الاصطناعي (Android, RTL)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_database: ^11.1.0
  http: ^1.2.2
  flutter_sound: ^9.2.13
  shared_preferences: ^2.3.2
  intl: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/backend/config/daily_plan.json
